name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        # test on same versions as fonttools
        python-version: ["3.10"]
        platform: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install packages
        run: |
          pip install .
          pip install pytest
      - name: Run Tests
        run: |
          pytest tests/
        env:
          GH_TOKEN: ${{ github.token }}